[project]
site_name = "Karva"
site_url = "https://matthewmckee4.github.io/karva"
site_description = "A Python test framework, written in Rust"
site_author = "Matthew McKee"
repo_url = "https://github.com/MatthewMckee4/karva"
repo_name = "MatthewMckee4/karva"

docs_dir = "docs"
site_dir = "site"
dev_addr = "localhost:3000"

extra_css = ["stylesheets/extra.css"]

nav = [
    { "Home" = "index.md"},
    { "Get Started" = [
        { "Installation" = "installation.md"},
        { "Tutorial" = "tutorial.md"},
    ]},
    { "Usage" = [
        { "Running Tests" = [
            { "Filtering Tests" = "usage/filtering.md"},
            { "Parallel Execution" = "usage/parallel.md"},
            { "Watch Mode" = "usage/watch.md"},
            { "Cache" = "usage/cache.md"},
        ]},
        { "Failure Handling" = [
            { "Failing Fast" = "usage/fail-fast.md"},
            { "Retries" = "usage/retries.md"},
            { "Slow Tests" = "usage/slow-tests.md"},
        ]},
        { "Writing Tests" = [
            { "Snapshots" = "usage/snapshots.md"},
            { "Coverage" = "usage/coverage.md"},
            { "Other Functions" = "usage/functions.md"},
        ]},
        { "Fixtures" = [
            { "Fixtures" = "usage/fixtures/fixtures.md"},
            { "Built In" = "usage/fixtures/builtin.md"},
        ]},
        { "Tags" = [
            { "Parametrize" = "usage/tags/parametrize.md"},
            { "Skip" = "usage/tags/skip.md"},
            { "Expect Fail" = "usage/tags/expect_fail.md"},
            { "Timeout" = "usage/tags/timeout.md"},
        ]},
    ]},
    { "Configuration" = [
        { "Configuration" = "configuration.md"},
        { "Profiles" = "profiles.md"},
    ]},
    { "Reference" = [
        { "CLI" = "cli.md"},
        { "Environment Variables" = "env-vars.md"},
    ]},
]

[project.theme]
language = "en"
features = [
    "navigation.instant",
    "navigation.tabs",
    "navigation.tabs.sticky",
    "navigation.sections",
    "navigation.top",
    "search.highlight",
]

[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
primary = "custom"
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
primary = "custom"
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to light mode"

[project.markdown_extensions.pymdownx.highlight]
linenums = true
auto_title = true

[project.markdown_extensions.pymdownx.superfences]
