use std::num::NonZeroUsize;

/// Documentation metadata for a single environment variable. Generated by the
/// [`env_vars!`] macro and consumed by `karva_dev` to build `docs/env-vars.md`.
pub struct EnvVarDoc {
    pub name: &'static str,
    /// Raw doc-comment lines as written above the constant. Each entry includes
    /// the leading space rustc captures from `///` (consumers should trim it).
    pub doc_lines: &'static [&'static str],
}

/// Defines a unit struct of `&'static str` environment-variable name constants
/// and exposes a `METADATA: &'static [EnvVarDoc]` slice next to it for
/// documentation generation.
macro_rules! env_vars {
    (
        $(#[doc = $struct_doc:literal])*
        $vis:vis struct $struct:ident {
            $(
                $(#[doc = $doc:literal])*
                pub const $name:ident: &'static str = $value:literal;
            )*
        }
    ) => {
        $(#[doc = $struct_doc])*
        $vis struct $struct;

        impl $struct {
            $(
                $(#[doc = $doc])*
                pub const $name: &'static str = $value;
            )*

            /// Documentation metadata for every variable on this struct, in
            /// declaration order.
            pub const METADATA: &'static [$crate::EnvVarDoc] = &[
                $(
                    $crate::EnvVarDoc {
                        name: $value,
                        doc_lines: &[$($doc),*],
                    },
                )*
            ];
        }
    };
}

env_vars! {
    /// Environment variables that Karva itself reads from the environment.
    pub struct EnvVars {
        /// This is a standard Rayon environment variable.
        pub const RAYON_NUM_THREADS: &'static str = "RAYON_NUM_THREADS";

        /// This is a standard Karva environment variable.
        pub const KARVA_MAX_PARALLELISM: &'static str = "KARVA_MAX_PARALLELISM";

        /// This is a standard Karva environment variable.
        pub const KARVA_CONFIG_FILE: &'static str = "KARVA_CONFIG_FILE";

        /// When set to "1" or "true", snapshot assertions write directly to `.snap`
        /// instead of creating `.snap.new` pending files.
        pub const KARVA_SNAPSHOT_UPDATE: &'static str = "KARVA_SNAPSHOT_UPDATE";
    }
}

env_vars! {
    /// Environment variables that the Karva worker sets on the test process so
    /// running tests can read them at runtime.
    pub struct WorkerEnvVars {
        /// Always set to `"1"`. The cheapest signal that test code is running
        /// under Karva, useful for fixtures and helpers that want to detect
        /// the runner without heavier introspection.
        pub const KARVA: &'static str = "KARVA";

        /// 0-indexed worker number. The canonical way to partition shared
        /// resources (database names, ports, scratch directories) across
        /// parallel workers without coordination.
        pub const KARVA_WORKER_ID: &'static str = "KARVA_WORKER_ID";

        /// Unique identifier (UUID) for a single `karva test` invocation,
        /// shared by every worker. Useful for correlating logs and external
        /// artifacts produced across multiple worker processes.
        pub const KARVA_RUN_ID: &'static str = "KARVA_RUN_ID";

        /// Absolute path to the directory Karva resolved as the project root.
        /// Saves tests from re-deriving the root via `__file__` walking or
        /// `os.getcwd()` heuristics.
        pub const KARVA_WORKSPACE_ROOT: &'static str = "KARVA_WORKSPACE_ROOT";

        /// Qualified name of the currently running test, e.g.
        /// `pkg.module::test_foo(value=1)`. Updated before each attempt.
        pub const KARVA_TEST_NAME: &'static str = "KARVA_TEST_NAME";

        /// The 1-indexed attempt number for the currently running test. Always
        /// set; `"1"` when no retries are configured.
        pub const KARVA_ATTEMPT: &'static str = "KARVA_ATTEMPT";

        /// The total number of attempts allowed for the currently running test
        /// (`retries + 1`). Always set.
        pub const KARVA_TOTAL_ATTEMPTS: &'static str = "KARVA_TOTAL_ATTEMPTS";

        /// Name of the active configuration profile, e.g. `"default"` or
        /// whatever was passed to `--profile` / `KARVA_PROFILE`.
        pub const KARVA_PROFILE: &'static str = "KARVA_PROFILE";

        /// Configured number of worker processes for this run. Mirrors
        /// `--num-workers` (capped to the number of useful workers).
        pub const KARVA_TEST_THREADS: &'static str = "KARVA_TEST_THREADS";

        /// Version of the running karva CLI.
        pub const KARVA_VERSION: &'static str = "KARVA_VERSION";
    }
}

pub fn max_parallelism() -> NonZeroUsize {
    std::env::var(EnvVars::KARVA_MAX_PARALLELISM)
        .or_else(|_| std::env::var(EnvVars::RAYON_NUM_THREADS))
        .ok()
        .and_then(|s| s.parse().ok())
        .unwrap_or_else(|| std::thread::available_parallelism().unwrap_or(NonZeroUsize::MIN))
}
