use std::num::NonZeroUsize;

/// Documentation metadata for a single environment variable. Generated by the
/// [`env_vars!`] macro and consumed by `karva_dev` to build `docs/env-vars.md`.
pub struct EnvVarDoc {
    pub name: &'static str,
    /// Raw doc-comment lines as written above the constant. Each entry includes
    /// the leading space rustc captures from `///` (consumers should trim it).
    pub doc_lines: &'static [&'static str],
}

/// Defines a unit struct of `&'static str` environment-variable name constants
/// and exposes a `METADATA: &'static [EnvVarDoc]` slice next to it for
/// documentation generation.
macro_rules! env_vars {
    (
        $(#[doc = $struct_doc:literal])*
        $vis:vis struct $struct:ident {
            $(
                $(#[doc = $doc:literal])*
                pub const $name:ident: &'static str = $value:literal;
            )*
        }
    ) => {
        $(#[doc = $struct_doc])*
        $vis struct $struct;

        impl $struct {
            $(
                $(#[doc = $doc])*
                pub const $name: &'static str = $value;
            )*

            /// Documentation metadata for every variable on this struct, in
            /// declaration order.
            pub const METADATA: &'static [$crate::EnvVarDoc] = &[
                $(
                    $crate::EnvVarDoc {
                        name: $value,
                        doc_lines: &[$($doc),*],
                    },
                )*
            ];
        }
    };
}

env_vars! {
    /// Environment variables that Karva itself reads from the environment.
    pub struct EnvVars {
        /// This is a standard Rayon environment variable.
        pub const RAYON_NUM_THREADS: &'static str = "RAYON_NUM_THREADS";

        /// This is a standard Karva environment variable.
        pub const KARVA_MAX_PARALLELISM: &'static str = "KARVA_MAX_PARALLELISM";

        /// This is a standard Karva environment variable.
        pub const KARVA_CONFIG_FILE: &'static str = "KARVA_CONFIG_FILE";

        /// When set to "1" or "true", snapshot assertions write directly to `.snap`
        /// instead of creating `.snap.new` pending files.
        pub const KARVA_SNAPSHOT_UPDATE: &'static str = "KARVA_SNAPSHOT_UPDATE";
    }
}

env_vars! {
    /// Environment variables that the Karva worker sets on the test process so
    /// running tests can read them at runtime.
    pub struct WorkerEnvVars {
        /// The 1-indexed attempt number for the currently running test. Always
        /// set; `"1"` when no retries are configured.
        pub const KARVA_ATTEMPT: &'static str = "KARVA_ATTEMPT";

        /// The total number of attempts allowed for the currently running test
        /// (`retries + 1`). Always set.
        pub const KARVA_TOTAL_ATTEMPTS: &'static str = "KARVA_TOTAL_ATTEMPTS";
    }
}

pub fn max_parallelism() -> NonZeroUsize {
    std::env::var(EnvVars::KARVA_MAX_PARALLELISM)
        .or_else(|_| std::env::var(EnvVars::RAYON_NUM_THREADS))
        .ok()
        .and_then(|s| s.parse().ok())
        .unwrap_or_else(|| std::thread::available_parallelism().unwrap_or(NonZeroUsize::MIN))
}
